# .streamlit/secrets.toml

[connections.snowflake]
account = "IVIRBXE-HO79754"
user = "ChillybananaTraining"
password = "twinC@M17snowflake"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
